apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: fe
      image: danieltuttle/k8s-test:fe
      ports:
        - containerPort: 8080
    - name: be
      image: danieltuttle/k8s-test:be
      ports:
        - containerPort: 5000
